version: "3"
services:
  web_server:
    build:
      context: ./nginx
      dockerfile: ./dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  
  app:
    build:
      context: ./app
      dockerfile: ./dockerfile
    expose:
      - 8080
    restart: always
  